const TestmonialsCards = [
  {
    id: 1,
    image:"/images/clientOne.jpg",
    rating: 4.5,
    descriptionOne: "“LINEA Interiors showed a strong understanding of space planning and design balance. The concepts were clean, modern, and practical for real-world execution.”",
    descriptionTwo: "“Clear communication and structured design process.”",
    name: "Ahmad Raza",
    title: "CEO AR Construction",
  },
  {
     id: 2,
    image:"/images/clientTwo.jpg",
    rating: 5,
    descriptionOne: "”The 3D visualizations were clear and realistic, which made decision-making much easier. The overall design process felt structured and professional.”",
    descriptionTwo: "“Strong focus on usability and spatial balance.”",
    name: "Bilal Khan",
    title: "Manager Vertex Co.",
  },
  {
     id: 3,
    image:"/images/clientThree.jpg",
    rating: 4,
    descriptionOne: "“The attention to proportions, materials, and layout details was impressive. The final design felt refined without being overdone.”",
    descriptionTwo: "“Design decisions backed by clarity and intent.”",
    name: "Hassan Malik",
    title: "Founder Urban Studio",
  },
  {
     id: 4,
    image:"/images/clientFour.jpg",
    rating: 5,
    descriptionOne: "“From initial concepts to final visuals, the workflow was smooth and efficient. The designs were thoughtful and aligned well with functional needs.”",
    descriptionTwo: "“A smooth workflow from concept to visualization.”",
    name: "Usman Sheikh",
    title: "CEO Prime Spaces LTD",
  },
  {
     id: 5,
    image:"/images/clientFive.jpg",
    rating: 5,
    descriptionOne: "“LINEA Interiors demonstrated a refined approach to layout and spatial balance. The concepts were modern, minimal, and thoughtfully executed.”",
    descriptionTwo: "“Minimal design with a strong functional approach.”",
    name: "Daniel Carter",
    title: "CEO Carter & Co",
  },
  {
     id: 6,
    image:"/images/clientSix.jpg",
    rating: 5,
    descriptionOne: "“The clarity in design thinking and visual presentation stood out. The 3D concepts communicated ideas effectively and reduced unnecessary revisions.”",
    descriptionTwo: "“Design decisions backed by clarity and intent.”",
    name: "David Thompson ",
    title: "CEO North Studio ",
  },
  {
     id: 7,
    image:"/images/clientSeven.jpg",
    rating: 5,
    descriptionOne: "“LINEA Interiors presented a clean and structured design approach. The layouts felt intentional, modern, and well-aligned with contemporary interior standards.”",
    descriptionTwo: "“Strong focus on usability and spatial balance.”",
    name: "Oliver Bennett ",
    title: "CEO Bennet Studio  ",
  },
  {
     id: 8,
    image:"/images/clientEight.jpg",
    rating: 5,
    descriptionOne: "“The design concepts were clear, functional, and visually refined. The process felt efficient and well thought out from start to finish.”",
    descriptionTwo: "“Minimal design with a strong functional approach.”",
    name: "Ryan Mitchell ",
    title: "CEO M.D Consultants  ",
  }
];

export { TestmonialsCards };
